# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-20 03:30
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utopia_cms_library', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='title'),
        ),
        migrations.AddField(
            model_name='bookcategory',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, null=True, populate_from='name'),
        ),
    ]
