# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-20 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('utopia_cms_library', '0002_auto_20221020_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksNewsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='date')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('header', models.TextField(blank=True, null=True, verbose_name='header')),
                ('footer', models.TextField(blank=True, null=True, verbose_name='footer')),
            ],
            options={
                'verbose_name': 'books newsletter',
                'verbose_name_plural': 'books newsletters',
                'ordering': ('-day',),
                'get_latest_by': 'day',
            },
        ),
        migrations.CreateModel(
            name='BooksNewsletterBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='order')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('footer', models.TextField(blank=True, null=True, verbose_name='footer')),
            ],
        ),
        migrations.CreateModel(
            name='BooksNewsletterBlockContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BooksNewsletterBlockRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='order')),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='text content')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utopia_cms_library.BooksNewsletterBlockContent')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utopia_cms_library.Book', verbose_name='book')),
            ],
        ),
        migrations.AddField(
            model_name='booksnewsletterblockcontent',
            name='books',
            field=models.ManyToManyField(through='utopia_cms_library.BooksNewsletterBlockRow', to='utopia_cms_library.Book', verbose_name='books'),
        ),
        migrations.AddField(
            model_name='booksnewsletterblock',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utopia_cms_library.BooksNewsletterBlockContent', verbose_name='content'),
        ),
        migrations.AddField(
            model_name='booksnewsletterblock',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='utopia_cms_library.BooksNewsletter'),
        ),
    ]
