# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-21 17:16
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('utopia_cms_library', '0003_auto_20221020_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksnewsletter',
            name='footer',
            field=django_markdown.models.MarkdownField(blank=True, null=True, verbose_name='footer'),
        ),
        migrations.AlterField(
            model_name='booksnewsletter',
            name='header',
            field=django_markdown.models.MarkdownField(blank=True, null=True, verbose_name='header'),
        ),
        migrations.AlterField(
            model_name='booksnewsletterblock',
            name='footer',
            field=django_markdown.models.MarkdownField(blank=True, null=True, verbose_name='footer'),
        ),
        migrations.AlterField(
            model_name='booksnewsletterblockrow',
            name='text_content',
            field=django_markdown.models.MarkdownField(blank=True, null=True, verbose_name='text content'),
        ),
    ]
