# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-25 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utopia_cms_library', '0004_auto_20221021_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booksnewsletterblock',
            options={'verbose_name': 'books newsletter block', 'verbose_name_plural': 'books newsletter blocks'},
        ),
        migrations.AlterModelOptions(
            name='booksnewsletterblockcontent',
            options={'verbose_name': 'books newsletter block content', 'verbose_name_plural': 'books newsletter block contents'},
        ),
        migrations.AlterModelOptions(
            name='booksnewsletterblockrow',
            options={'verbose_name': 'books newsletter block row', 'verbose_name_plural': 'books newsletter block rows'},
        ),
        migrations.AddField(
            model_name='book',
            name='cover_photo_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers', verbose_name='cover photo mobile version'),
        ),
        migrations.AlterField(
            model_name='booksnewsletterblock',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='utopia_cms_library.BooksNewsletter'),
        ),
    ]
