# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-08 17:33
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('utopia_cms_library', '0005_auto_20221025_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=django_markdown.models.MarkdownField(blank=True, null=True, verbose_name='description'),
        ),
    ]
