# Generated by Django 2.2.28 on 2023-06-11 13:51

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utopia_cms_library', '0006_auto_20221108_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, blank=True, editable=False, max_length=255, null=True, populate_from='title', unique=True),
        ),
    ]
